# Site settings
title: Tidal Theory
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tidaltheory.co" # the base hostname & protocol for your site

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/

twitter_username: stormwarning
github_username:  stormwarning

# Build settings
permalink: pretty
markdown: kramdown

exclude: [node_modules, source, bower.json, gulpfile.js, package.json, gemfile]
